### ISSUE TITLE
If `event_handlers` exist in Agora's configuration, the following error occurs

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#2259]
If `event_handlers` exist in Agora's configuration, the following error occurs:
```
Attaching to rns-test-env_agora_1
agora_1  | Agora initialization failed! The following Exception might help: object.Exception@submodules/vibe.d/inet/vibe/inet/url.d(150): Schema must start with an alphabetical char, found: [
agora_1  | ----------------
agora_1  | /usr/include/d/std/exception.d:513 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55f54bc070d0]
agora_1  | /usr/include/d/std/container/slist.d:585 pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x55f54bb15590]
agora_1  | submodules/vibe.d/inet/vibe/inet/url.d:142 ref @safe vibe.inet.url.URL vibe.inet.url.URL.__ctor(immutable(char)[]) [0x55f54c399fa0]
agora_1  | source/agora/network/Manager.d:1265 vibe.web.rest.RestInterfaceSettings agora.network.Manager.NetworkManager.getRestInterfaceSettings(immutable(char)[]) [0x55f54bb6b2d0]
agora_1  | source/agora/network/Manager.d:1212 agora.api.Handlers.BlockExternalizedHandler agora.network.Manager.NetworkManager.getBlockExternalizedHandler(immutable(char)[]) [0x55f54bb60040]
agora_1  | source/agora/node/FullNode.d:279 agora.api.Handlers.BlockExternalizedHandler agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda7!(immutable(char)[]).__lambda7(immutable(char)[]) [0x55f54bb5ffc0]
agora_1  | /usr/include/d/std/algorithm/iteration.d:951 std.typecons.Flag!("each").Flag std.algorithm.iteration.each!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda7).each!(std.algorithm.iteration.MapResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda6, std.algorithm.iteration.MapResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda5, std.algorithm.iteration.FilterResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda4, immutable(agora.common.Config.EventHandlerConfig)[]).FilterResult).MapResult).MapResult).each(std.algorithm.iteration.MapResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda6, std.algorithm.iteration.MapResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda5, std.algorithm.iteration.FilterResult!(agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config).__lambda4, immutable(agora.common.Config.EventHandlerConfig)[]).FilterResult).MapResult).MapResult) [0x55f54bb5aff0]
agora_1  | source/agora/node/FullNode.d:243 agora.node.FullNode.FullNode agora.node.FullNode.FullNode.__ctor(agora.common.Config.Config) [0x55f54bb32700]
agora_1  | source/agora/node/Validator.d:85 agora.node.Validator.Validator agora.node.Validator.Validator.__ctor(agora.common.Config.Config) [0x55f54bb32370]
agora_1  | source/agora/node/Runner.d:63 std.typecons.Tuple!(agora.node.FullNode.FullNode, "node", agora.node.admin.AdminInterface.AdminInterface, "admin", agora.flash.Node.AgoraFlashNode, "flash", vibe.http.server.HTTPListener[], "http").Tuple agora.node.Runner.runNode(agora.common.Config.Config) [0x55f54bb2ed60]
agora_1  | source/agora/node/main.d:176 nothrow void agora.node.main.main(immutable(char)[][]).__lambda15() [0x55f54bb2eb50]
agora_1  | submodules/vibe-core/source/vibe/core/task.d:708 nothrow void vibe.core.task.TaskFuncInfo.set!(void delegate() nothrow).set(ref void delegate() nothrow).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x55f54bc490b0]
agora_1  | submodules/vibe-core/source/vibe/core/task.d:737 void vibe.core.task.TaskFuncInfo.call() [0x55f54c469fe0]Main thread exiting
agora_1  | 
agora_1  | submodules/vibe-core/source/vibe/core/task.d:403 nothrow void vibe.core.task.TaskFiber.run() [0x55f54c4694e0]
agora_1  | ??:? fiber_entryPoint [0x7f22ade6e0a0]
```

**Comment by Geod24** [comment]
Can you show which configuration you used ? And which version of Agora (`agora --version`).

**Comment by MichaelKim20** [comment]
I used this 
```
event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  block_externalized:
    - http://stoa:3836/block_externalized
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  preimage_received:
    - http://stoa:3836/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  transaction_received:
    - http://stoa:3836/transaction_received
```
