### ISSUE TITLE
Improve `addresses_to_register` configuration UX

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2320]
Currently, we have `addresses_to_register` under `validator` config.
This has a few issues:
- It requires to specify the protocol being used, e.g. `http://` or `https://`;
- It essentially duplicates configuration (because we have `interfaces` entries);
- Misconfiguration can easily result in hard-to-debug issues;

One suggestion would be to move the address to register to the interface entry, so that we can remove the duplication we have with the protocol. Also bear in mind that our `interface` type might be `http` but if a certificate is present, it's actually going to bind to `https`.

Another is to look up methods to find the IP address of the node, or even its domain name.
Such functions include:
- [gethostname](https://man7.org/linux/man-pages/man2/gethostname.2.html);
- [getaddrinfo](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html);
- [rDNS lookup](https://en.wikipedia.org/wiki/Reverse_DNS_lookup);
- Another external service (à la http://www.mon-ip.com/en/my-ip/ );

Example configuration:
```YAML
interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826
    register: true
```
The above would attempt to first determine the domain name, then the IP address of the listening interface;

```YAML
interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826
    register: "node1.bosagora.io"
```
The above would assume that the listening interface is bound to the specified domain name.

**Comment by Geod24** [comment]
@mkykadir Mentioned in the other issue:
> Kinda, I feel explanation of that issue still directs me to provide full URL during registration (using `interface` fields) but prevent duplication by moving configuration field under `interfaces`. I think we shouldn't force users to provide full URL for registration.

By full URL, you mean, including the schema right ? I was thinking about this today, and figured we could simplify it by using:
```yaml
interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826
    public: true
    hostname: "node1.bosagora.io"
```

`public: true` would be the default, if one does not want to register an interface, they may set it to `false`.
Regarding the `hostname`, it seems like a common enough need to warrant an `@Optional` field here. We could use the IP as a default, or try to do a reverse lookup.
Additionally to this, we should keep a field similar to `addresses_to_register`, where full URL are provided. It would be a case of last resort where the port / protocol is not the public one (e.g. Nginx as an HTTPS front to an HTTP interface).

What do you think ?
