### ISSUE TITLE
DNS: Implement whitelisting for AXFR

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2647]
We should have a way to restrict AXFR to whitelisted clients, so that it doesn't get abused.
A config file entry, probably at the registry level, as it doesn't make much sense to have it at the zone level, would be needed.

```yaml
registry:
  enabled: true
  whitelist:
    - 1.2.3.4
    - foo.bar
```
