### ISSUE TITLE
Allow merging `stats` interface with an `http[s]` one

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2888]
Currently, we can have both `stats` and `http` interface:
https://github.com/bosagora/agora/blob/1d67da7e16f0233d20bbb9f0175c08bdecd81dc6/doc/config.example.yaml#L67-L78

However, we might want to have them on the same port (e.g. if the interface is meant to be public).
In which case, the following should use the same `URLRouter`:
```YAML
interfaces:
  - type: http
    address: "0.0.0.0"
    port: 8080
  - type: stats
    address: "0.0.0.0"
    port: 8080
```

Questions:
- What happens when `https` is used instead of `http` ? I'm tempted to say same behavior.
- What happens when the `address` differs but the `port` is the same ? Having both `127.0.0.1` and `0.0.0.0` will conflict (because `0.0.0.0` includes `127.0.0.1`). Perhaps we can just error out.

Side note: Having a way to bind to an interface instead of an address would be *really* nicer.
